"""add_trakt_user_auth_table

Revision ID: 283dc8c29b88
Revises: b2b81bfd4375
Create Date: 2025-06-17 18:08:04.469892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283dc8c29b88'
down_revision: Union[str, Sequence[str], None] = 'b2b81bfd4375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traktuserauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traktuserauth_access_token'), 'traktuserauth', ['access_token'], unique=False)
    op.create_index(op.f('ix_traktuserauth_user_id'), 'traktuserauth', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traktuserauth_user_id'), table_name='traktuserauth')
    op.drop_index(op.f('ix_traktuserauth_access_token'), table_name='traktuserauth')
    op.drop_table('traktuserauth')
    # ### end Alembic commands ###
